# Generated by Django 4.1 on 2025-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(blank=True, to="octofit_tracker.user"),
        ),
    ]
